version: '3.8'

services:
  api-apptrack:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-apptrack:latest
    container_name: api_apptrack
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/apptrackdb?schema=public"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apptrackdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    ports:
      - "6432:6432"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - ./pgbouncer:/etc/pgbouncer
    depends_on:
      - db

volumes:
  postgres_data:
