version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres/:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    networks:
      - network

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_HOST=postgres
      - DB_NAME=docker
      - POOL_MODE=transaction
      - ADMIN_USERS=docker
      - AUTH_TYPE=plain
    ports:
      - '6432:5432'
    depends_on:
      - postgres
    networks:
      - network

  migration:
    image: apitrack
    command: >
      sh -c "
        npx prisma migrate deploy
      "
    depends_on:
      - pgbouncer
    environment:
      DATABASE_URL: 'postgresql://docker:docker@postgres:5432/docker?schema=public'
    networks:
      - network

  api:
    image: apitrack
    ports:
      - '3000:3000'
    depends_on:
      - migration
    networks:
      - network

networks:
  network:
    driver: bridge
